/* 
	჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻
	჻჻  
	჻჻  ELYVION | HOLDING - (Previously Kreygers | Group)
	჻჻
	჻჻  Description : Launches the "menuprinc.hpp" dialog and controls its scrolling.
	჻჻
	჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻჻ 
*/

createDialog "menuprinc";
enableEnvironment [false, false];

((uiNamespace getVariable "menuprinc")displayCtrl 1002) ctrlShow false;
((uiNamespace getVariable "menuprinc")displayCtrl 1003) ctrlShow false;

[] spawn {
	while { true } do {
		["videos\MenuBackground.ogv"] call BIS_fnc_playVideo;
	};
};

//჻჻ Not recommended, not optimized
[] spawn {
	while { true } do {
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (1).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (2).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (3).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (4).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (5).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (6).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (7).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (8).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (9).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (10).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (11).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (12).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (13).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (14).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (15).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (16).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (17).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (18).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (19).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (20).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (21).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (22).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (23).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (24).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (25).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (26).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (27).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (28).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (29).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (30).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (31).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (32).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (33).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (34).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (35).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (36).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (37).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (38).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (39).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (40).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (41).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (42).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (43).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (44).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (45).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (46).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (47).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (48).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (49).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (50).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (51).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (52).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (53).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (54).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (55).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (56).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (57).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (58).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (59).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (60).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (61).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (62).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (63).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (64).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (65).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (66).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (67).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (68).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (69).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (70).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (71).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (72).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (73).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (74).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (75).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (76).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (77).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (78).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (79).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (80).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (81).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (82).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (83).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (84).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (85).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (86).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (87).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (88).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (89).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (90).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (91).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (92).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (93).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (94).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (95).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (96).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (97).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (98).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (99).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (100).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (101).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (102).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (103).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (104).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (105).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (106).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (107).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (108).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (109).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (110).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (111).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (112).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (113).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (114).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (115).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (116).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (117).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (118).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (119).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (120).jpg";
			sleep 0.05;
			((uiNamespace getVariable "menuprinc")displayCtrl 1001) ctrlSetText "textures\animatedbackground\bimg (121).jpg";
			sleep 0.05;
		};
};

((uiNamespace getVariable "menuprinc")displayCtrl 1002) ctrlShow true;
((uiNamespace getVariable "menuprinc")displayCtrl 1002) ctrlSetFade 1;
((uiNamespace getVariable "menuprinc")displayCtrl 1002) ctrlCommit 0;
((uiNamespace getVariable "menuprinc")displayCtrl 1002) ctrlSetFade 0;
((uiNamespace getVariable "menuprinc")displayCtrl 1002) ctrlCommit 3;

((uiNamespace getVariable "menuprinc")displayCtrl 1003) ctrlShow true;
((uiNamespace getVariable "menuprinc")displayCtrl 1003) ctrlSetFade 1;
((uiNamespace getVariable "menuprinc")displayCtrl 1003) ctrlCommit 0;
((uiNamespace getVariable "menuprinc")displayCtrl 1003) ctrlSetFade 0;
((uiNamespace getVariable "menuprinc")displayCtrl 1003) ctrlCommit 2;

Enter_keyDownEHId = (findDisplay 46) displayAddEventHandler ["KeyDown", "if ((_this select 1) == 28) then { [] execVM ""menu\files\menuprincex2.sqf"" }"];
